### PR TITLE
Added more inequality predicates

### PR DESCRIPTION
**Pull request by mikelodder7**
Signed-off-by: Michael Lodder <redmike7@gmail.com>

### CODE REVIEW

**Comment by ArthurManz** [comment]
Any idea when this would be merged and when could we use it in Indy SDK?

**Comment by mikelodder7** [comment]
Talk to the maintainers. I’m hoping not too long.

**Comment by ArthurManz** [comment]
I will ask on the Slack channel! Thanks! :smile:

**Comment by jovfer** [comment]
> They are internal. Indy-SDK would not see any of this.
@mikelodder7 @brentzundel Unfortunately it's not true. This PR contains breaking changes. And new master is incompatible with current stable.

**Comment by jovfer** [comment]
@mikelodder7 
IndySDK use `ProofBuilder` like
```
Prover::new_proof_builder();
...
.add_sub_proof_request
...
.finalize() -> Proof
```
then IndySDK serialize `Proof` as part of output JSON string for application. This string is used by Proover to present the proof for Verifier
```
pub struct Proof {
    proofs: Vec<SubProof>,
    aggregated_proof: AggregatedProof,
}
...
pub struct SubProof {
    primary_proof: PrimaryProof,
    non_revoc_proof: Option<NonRevocProof>
}
...
pub struct PrimaryProof {
    eq_proof: PrimaryEqualProof,
    ~ge_proofs: Vec<PrimaryPredicateGEProof>~ now changed to
    ne_proofs: Vec<PrimaryPredicateInequalityProof>
}
```

**Comment by jovfer** [comment]
1) The easiest way may be to just "duplicate" `ge_proofs` field and add 3 new like `gt_proofs`, `le_proofs` and `lt_proofs`.
2) AFAIR design discussion there is an option to create new anoncreds type. Now it's "CL" but we can implement the new one. I don't like this option, as current changes is just extending existing implementation to fit math model.
3) we can try to introduce versioning here. E.g. append ver field and assume omitted as ver.0

@mikelodder7 please share your options too
@vimmerru have I forgotten smth from our discussions about versioning in IndyCrypto?

**Comment by mikelodder7** [comment]
I vote for option 3,1,2 in that order. The problem occurs when deserializing in that in consumes the stream so you can only convert once. So what have you done before to handle this?

**Pull request merged**
