### PR TITLE
Updates to anoncreds

### PR DESCRIPTION
**Pull request by mikelodder7**
These updates allow multiple hidden attributes and not just the master secret.

Also commitments to attributes can be used.

### CODE REVIEW

**Comment by mikelodder7** [comment]
Yes but there will need be some indy-sdk changes to handle it. So for example. Instead of hardcoding the attribute master secret as a property in the code, indy-sdk can add it as a hidden attribute for issuance and common attribute for proofs. Other than that everything should still work.

**Comment by vimmerru** [comment]
@mikelodder7 

To be more clear:

1. We have credential issued with current indy-crypto stable
2. We want to make proof and verify it with your PR

Will it work? Do we have all serialization and math compatible?

**Comment by vimmerru** [comment]
@mikelodder7 

To merge this PR we will need that all indy-sdk tests pass after this PR. Have you tried this?

**Comment by vimmerru** [comment]
@jovfer 

Could you try to execute libindy tests with this branch of indy-crypto?

**Comment by jovfer** [comment]
@vimmerru this PR contains public API changes, so it incompatible with current libindy master at compile time

**Comment by mikelodder7** [comment]
Do I need to make a PR for indy-sdk to fix any tests to match this PR?

**Comment by vimmerru** [comment]
We need this PR to merge this. Also it must be merged before 1.5 release of libindy if there will be Credentails format interoperability issues. Otherwise we will need to make this code as new signature type.

**Pull request merged**
